name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install tree, gcc, make, xorg, libxext-dev, libbsd-dev, valgrind, lolcat & neofetch
      run: sudo apt-get install tree gcc make xorg libxext-dev libbsd-dev valgrind lolcat neofetch

    - name: Install norminette
      run: pip install norminette

    - name: ==========] Enter ft_printf [==========
      run: cd ft_printf

    - name: Run tree
      run: tree

    - name: Run norminette
      run: norminette src include

    - name: Make program as module
      run: make module

    - name: View Contents of bin
      run: ls -la obj/

    - name: Clean output
      run: make clean

    - name: Make program as standalone
      run: make all

    - name: Re-make program
      run: make re

    - name: View Contents of standalone
      run: nm -C build/libftprintf.a

    - name: ==========] Exit ft_printf [==========
      run: cd ..
    
    - name: ==========] Enter get_next_line [==========
      run: cd get_next_line

    - name: Run tree
      run: tree

    - name: Run norminette
      run: norminette src include

    - name: Make program as module
      run: make module

    - name: View Contents of bin
      run: ls -la obj/

    - name: Clean output
      run: make clean

    - name: Make program as standalone
      run: make all

    - name: Re-make program
      run: make re

    - name: View Contents of standalone
      run: nm -C build/libftgnl.a

    - name: ==========] Exit get_next_line [==========
      run: cd ..
    
    - name: ==========] Enter libft [==========
      run: cd libft

    - name: Run tree
      run: tree

    - name: Run norminette
      run: norminette src include

    - name: Make program
      run: make

    - name: Re-make program
      run: make re

    - name: View Contents of Libft
      run: nm -C build/libft.a
    
    - name: Run Tests
      run: make test

    - name: ==========] Exit libft [==========
      run: cd ..

