name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: ==========] ft_printf [==========
      uses: WOLFIE-OG/ft_printf@dev/.github/workflows/makefile.yml

    