name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Get figlet fonts
      run: git clone https://github.com/xero/figlet-fonts
    
    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install tree, gcc, make, xorg, libxext-dev, libbsd-dev, valgrind, lolcat, neofetch & figlet
      run: sudo apt-get install tree gcc make xorg libxext-dev libbsd-dev valgrind lolcat neofetch figlet

    - name: Install norminette
      run: pip install norminette

    - name: ==========] Run ft_printf [==========
      run: figlet -f figlet-fonts/3d.flf Running ft_printf

    - name: Run tree
      run: tree
      working-directory: ft_printf

    - name: Run norminette
      run: norminette src include
      working-directory: ft_printf

    - name: Make ft_printf as module
      run: make module
      working-directory: ft_printf

    - name: View contents of obj
      run: ls -la obj/
      working-directory: ft_printf

    - name: Clean output
      run: make clean
      working-directory: ft_printf

    - name: Make ft_printf as standalone
      run: make all
      working-directory: ft_printf

    - name: Re-make ft_printf
      run: make re
      working-directory: ft_printf

    - name: View contents of standalone
      run: nm -C build/libftprintf.a
      working-directory: ft_printf
    
    - name: ==========] Run get_next_line [==========
      run: figlet -f figlet-fonts/3d.flf Running get_next_line

    - name: Run tree
      run: tree
      working-directory: get_next_line

    - name: Run norminette
      run: norminette src include
      working-directory: get_next_line

    - name: Make get_next_li e as module
      run: make module
      working-directory: get_next_line

    - name: View contents of obj
      run: ls -la obj/
      working-directory: get_next_line

    - name: Clean output
      run: make clean
      working-directory: get_next_line

    - name: Make get_next_line as standalone
      run: make all
      working-directory: get_next_line

    - name: Re-make get_next_line
      run: make re
      working-directory: get_next_line

    - name: View contents of standalone
      run: nm -C build/libftgnl.a
      working-directory: get_next_line
    
    - name: ==========] Run libft [==========
      run: figlet -f figlet-fonts/3d.flf Running libft

    - name: Run tree
      run: tree
      working-directory: libft

    - name: Run norminette
      run: norminette src include
      working-directory: libft

    - name: Make libft
      run: make
      working-directory: libft

    - name: Re-make libft
      run: make re
      working-directory: libft

    - name: View contents of libft
      run: nm -C build/libft.a
      working-directory: libft
    
    - name: Run Tests
      run: make test
      working-directory: libft

    - name: ==========] Run born2beroot [==========
      run: figlet -f figlet-fonts/3d.flf Running born2beroot
    
    - name: Run monitor script
      run: bash monitoring.sh
      working-directory: born2beroot

    - name: ==========] Run minitalk [==========
      run: figlet -f figlet-fonts/3d.flf Running minitalk

    - name: Run tree
      run: tree
      working-directory: minitalk

    - name: Run norminette
      run: norminette src include
      working-directory: minitalk

    - name: Make minitalk server & client
      run: make
      working-directory: minitalk

    - name: Re-make minitalk server & client
      run: make re
      working-directory: minitalk

    - name: View contents of client
      run: nm -C client
      working-directory: minitalk
    
    - name: View contents of server
      run: nm -C server
      working-directory: minitalk
    