name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Get figlet fonts
      run: git clone https://github.com/xero/figlet-fonts
    
    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install tree, gcc, make, xorg, libxext-dev, libbsd-dev, valgrind, lolcat, neofetch & figlet
      run: sudo apt-get install tree gcc make xorg libxext-dev libbsd-dev valgrind lolcat neofetch figlet

    - name: Install norminette
      run: pip install norminette

    - name: ==========] Run ft_printf [==========
      run: figlet -f figlet-fonts/3d.flf Running ft_printf

    - name: Run tree
      run: tree
      working-directory: ft_printf

    - name: Run norminette
      run: norminette src include
      working-directory: ft_printf

    - name: Make ft_printf as a module
      run: make module
      working-directory: ft_printf

    - name: View contents of obj
      run: ls -la obj/
      working-directory: ft_printf

    - name: Clean output
      run: make clean
      working-directory: ft_printf

    - name: Make ft_printf as standalone
      run: make all
      working-directory: ft_printf

    - name: Re-make ft_printf
      run: make re
      working-directory: ft_printf

    - name: View contents of standalone
      run: nm -C build/libftprintf.a
      working-directory: ft_printf
    
    - name: ==========] Run get_next_line [==========
      run: figlet -f figlet-fonts/3d.flf Running get_next_line

    - name: Run tree
      run: tree
      working-directory: get_next_line

    - name: Run norminette
      run: norminette src include
      working-directory: get_next_line

    - name: Make get_next_line as a module
      run: make module
      working-directory: get_next_line

    - name: View contents of obj
      run: ls -la obj/
      working-directory: get_next_line

    - name: Clean output
      run: make clean
      working-directory: get_next_line

    - name: Make get_next_line as standalone
      run: make all
      working-directory: get_next_line

    - name: Re-make get_next_line
      run: make re
      working-directory: get_next_line

    - name: View contents of standalone
      run: nm -C build/libftgnl.a
      working-directory: get_next_line
    
    - name: ==========] Run libft [==========
      run: figlet -f figlet-fonts/3d.flf Running libft

    - name: Run tree
      run: tree
      working-directory: libft

    - name: Run norminette
      run: norminette src include
      working-directory: libft

    - name: Make libft
      run: make
      working-directory: libft

    - name: Re-make libft
      run: make re
      working-directory: libft

    - name: View contents of libft
      run: nm -C build/libft.a
      working-directory: libft
    
    - name: Run Tests
      run: make test
      working-directory: libft

    - name: ==========] Run born2beroot [==========
      run: figlet -f figlet-fonts/3d.flf Running born2beroot
    
    - name: Display monitor script
      run: cat monitoring.sh
      working-directory: born2beroot

    - name: ==========] Run minitalk [==========
      run: figlet -f figlet-fonts/3d.flf Running minitalk

    - name: Run tree
      run: tree
      working-directory: minitalk

    - name: Run norminette
      run: norminette src include libft/src libft/include
      working-directory: minitalk

    - name: Make minitalk server & client
      run: make
      working-directory: minitalk

    - name: Re-make minitalk server & client
      run: make re
      working-directory: minitalk

    - name: View contents of libft
      run: nm -C libft/build/libft.a
      working-directory: minitalk

    - name: View contents of client
      run: nm -C client
      working-directory: minitalk
    
    - name: View contents of server
      run: nm -C server
      working-directory: minitalk

    - name: ==========] Run so_long [==========
      run: figlet -f figlet-fonts/3d.flf Running so_long

    - name: Run tree
      run: tree
      working-directory: so_long

    - name: Run norminette
      run: norminette src include libs/libft/src libs/libft/include
      working-directory: so_long

    - name: Make so_long
      run: make
      working-directory: so_long

    - name: Re-make so_long
      run: make re
      working-directory: so_long

    - name: View contents of libft
      run: nm -C libs/libft/build/libft.a
      working-directory: so_long

    - name: View contents of minilibx
      run: nm -C libs/minilibx/libmlx_Linux.a
      working-directory: so_long
    
    - name: View contents of so_long
      run: nm -C so_long
      working-directory: so_long

    - name: ==========] Run push_swap [==========
      run: figlet -f figlet-fonts/3d.flf Running push_swap
    
    - name: Run tree
      run: tree
      working-directory: push_swap

    - name: Run norminette
      run: norminette src include libft/src libft/include
      working-directory: push_swap

    - name: Make push_swap
      run: make
      working-directory: push_swap

    - name: Re-make push_swap
      run: make re
      working-directory: push_swap

    - name: View contents of libft
      run: nm -C libft/build/libft.a
      working-directory: push_swap
    
    - name: View contents of push_swap
      run: nm -C push_swap
      working-directory: push_swap
    
    - name: Test - 10 (No Arg)
      run: ./tests/test_10.sh
      working-directory: push_swap

    - name: Test - 10
      run: ./tests/test_10_1_arg.sh
      working-directory: push_swap

    - name: Test - 50 (No Arg)
      run: ./tests/test_50.sh
      working-directory: push_swap

    - name: Test - 50
      run: ./tests/test_50_1_arg.sh
      working-directory: push_swap

    - name: Test - 100 (No Arg)
      run: ./tests/test_100.sh
      working-directory: push_swap

    - name: Test - 100
      run: ./tests/test_100_1_arg.sh
      working-directory: push_swap

    - name: Re-Make push_swap with debug
      run: make re CFLAGS+=-DDEBUG_PRINT=1
      working-directory: push_swap

    - name: Test - 10 (No Arg)
      run: ./tests/test_10.sh
      working-directory: push_swap

    - name: Test - 10
      run: ./tests/test_10_1_arg.sh
      working-directory: push_swap

    - name: Test - 50 (No Arg)
      run: ./tests/test_50.sh
      working-directory: push_swap

    - name: Test - 50
      run: ./tests/test_50_1_arg.sh
      working-directory: push_swap

    - name: Test - 100 (No Arg)
      run: ./tests/test_100.sh
      working-directory: push_swap

    - name: Test - 100
      run: ./tests/test_100_1_arg.sh
      working-directory: push_swap
