name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install tree, gcc, make, xorg, libxext-dev, libbsd-dev, valgrind, lolcat, neofetch & figlet
      run: sudo apt-get install tree gcc make xorg libxext-dev libbsd-dev valgrind lolcat neofetch figlet

    - name: Install norminette
      run: pip install norminette

    - name: ==========] Run ft_printf [==========
      run: figlet Running ft_printf | lolcat

    - name: Run tree
      run: tree
      working-directory: ft_printf

    - name: Run norminette
      run: norminette src include
      working-directory: ft_printf

    - name: Make program as module
      run: make module
      working-directory: ft_printf

    - name: View Contents of bin
      run: ls -la obj/
      working-directory: ft_printf

    - name: Clean output
      run: make clean
      working-directory: ft_printf

    - name: Make program as standalone
      run: make all
      working-directory: ft_printf

    - name: Re-make program
      run: make re
      working-directory: ft_printf

    - name: View Contents of standalone
      run: nm -C build/libftprintf.a
      working-directory: ft_printf
    
    - name: ==========] Run get_next_line [==========
      run: figlet Running get_next_line | lolcat

    - name: Run tree
      run: tree
      working-directory: get_next_line

    - name: Run norminette
      run: norminette src include
      working-directory: get_next_line

    - name: Make program as module
      run: make module
      working-directory: get_next_line

    - name: View Contents of bin
      run: ls -la obj/
      working-directory: get_next_line

    - name: Clean output
      run: make clean
      working-directory: get_next_line

    - name: Make program as standalone
      run: make all
      working-directory: get_next_line

    - name: Re-make program
      run: make re
      working-directory: get_next_line

    - name: View Contents of standalone
      run: nm -C build/libftgnl.a
      working-directory: get_next_line
    
    - name: ==========] Run libft [==========
      run: figlet Running libft | lolcat

    - name: Run tree
      run: tree
      working-directory: libft

    - name: Run norminette
      run: norminette src include
      working-directory: libft

    - name: Make program
      run: make
      working-directory: libft

    - name: Re-make program
      run: make re
      working-directory: libft

    - name: View Contents of Libft
      run: nm -C build/libft.a
      working-directory: libft
    
    - name: Run Tests
      run: make test
      working-directory: libft


